### ISSUE TITLE
[Client thread/ERROR] [tconevo]: Artifacts were looked up before being loaded!

### ISSUE THREAD

**Issue by Krutoy242** [phantamanta44/tinkers-evolution#31]
tconevo-1.12.2-1.0.28

`debug.log` have 37 errors like this. 
Can't see if it caused actual errors in game. Just want to know what this error means for my world.

```java
[Client thread/ERROR] [tconevo]: Artifacts were looked up before being loaded!
java.lang.IllegalStateException: null
	at xyz.phanta.tconevo.artifact.ArtifactRegistry.getAllArtifacts(ArtifactRegistry.java:72) [ArtifactRegistry.class:?]
	at xyz.phanta.tconevo.handler.ArtifactLootHandler.onLootTableLoaded(ArtifactLootHandler.java:51) [ArtifactLootHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3318_ArtifactLootHandler_onLootTableLoaded_LootTableLoadEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67) [LagGoggles-1.12.2-5.8-132.jar:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:775) [ForgeEventFactory.class:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1186) [ForgeHooks.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:156) [bfv$a.class:?]
```

Found another error in logs that can be related:
```java
[20:23:12] [Client thread/INFO] [tconevo]: Loading artifacts...
[20:23:12] [Client thread/ERROR] [tconevo]: Encountered exception while loading artifacts!
java.nio.file.NoSuchFileException: C:\Users\LD\Twitch\Minecraft\Instances\Enigmatica2Expert - Extended\config\tconevo\artifacts
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79) ~[?:1.8.0_251]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_251]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[?:1.8.0_251]
	at sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86) ~[?:1.8.0_251]
	at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:518) ~[?:1.8.0_251]
	at java.nio.file.Files.newDirectoryStream(Files.java:457) ~[?:1.8.0_251]
	at java.nio.file.Files.list(Files.java:3451) ~[?:1.8.0_251]
	at xyz.phanta.tconevo.artifact.ArtifactLoader.loadArtifacts(ArtifactLoader.java:35) [ArtifactLoader.class:?]
	at xyz.phanta.tconevo.CommonProxy.onPreInit(CommonProxy.java:82) [CommonProxy.class:?]
	at xyz.phanta.tconevo.client.ClientProxy.onPreInit(ClientProxy.java:41) [ClientProxy.class:?]
	at xyz.phanta.tconevo.TconEvoMod.onPreInit(TconEvoMod.java:56) [TconEvoMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
```

**Comment by phantamanta44** [comment]
it seems like tconevo is failing to load the artifact config directory, then every other piece of code that uses artifacts triggers the warning. i'll disable the error spam for now, but i'd like to get a full log to try and figure out why artifact loading is failing in the first place

**Comment by Krutoy242** [comment]
Ok, there is full log [debug.log](https://gist.github.com/Krutoy242/774d45a34e43f9d07add106b37553ae2)

**Comment by phantamanta44** [comment]
have you deleted the `artifacts` subfolder in the tconevo config folder?

**Comment by Krutoy242** [comment]
No. And it was never created. `tconevo` forlder have only empty `.config_version` file.

**Comment by phantamanta44** [comment]
i've just published 1.0.31, which adds more detailed logging for the config loading process. please try running the game with that version and sending over a new log when you have the time

**Comment by Krutoy242** [comment]
There, new [debug.log](https://www.dropbox.com/s/mm6icvocgyg5quz/debug.log?dl=0)

**Comment by phantamanta44** [comment]
I can't seem to find any reason for this issue. It might just be a one-time fluke...

For now, you may be able to fix it by just deleting the `.config_version` file, which *should* -- in theory -- regenerate all the artifacts.

**Comment by Krutoy242** [comment]
Yes, its works! I removed `.config_version` and on next lunch bunch of artifact files generated. Error in `debug.log` is fixed too 👍

**Comment by phantamanta44** [comment]
i still don't understand what happened here, but i'll just assume it's some sort of file system hiccup and not a real issue

**Comment by Krutoy242** [comment]
Its related to artifacts so i decided not create different issue.

I found this warnings in `debug.log`:
```
[Client thread/WARN] [tconevo]: Failed to initialize artifact "ancient_arrow": Unknown material "gelid_enderium"
[Client thread/WARN] [tconevo]: Failed to initialize artifact "stormbow": Unknown material "fluxed_string"
```
Btw, `gelid_enderium` and `fluxed_string` is exists in fluid form, but there is no actual uses for them.

[debug.log](https://www.dropbox.com/s/mm6icvocgyg5quz/debug.log?dl=0)

**Comment by phantamanta44** [comment]
not a bug; this is just telling you that these artifacts aren't loaded because the integrations they rely on aren't there (in this case, redstone repository)

**Comment by Krutoy242** [comment]
Oh, ok, thank you for exaplanation.
